package:
  name: interpretation
  version: 0.1.0

source:
  path: ../interpretation/

requirements:
  host:
    - python >=3.11,<3.12.0a0
    - numpy >=1.17.0
    - r-base >=4.3.1
    - r-devtools
    - r-optparse
    - r-devtools
    - r-zoo
    - h5py =3.9.0
    - keras =2.12.0
    - tensorflow =2.12.1

  run:
    - python >=3.11,<3.12.0a0
    - numpy >=1.17.0
    - r-base >=4.3.1
    - r-devtools
    - r-optparse
    - r-devtools
    - r-zoo
    - h5py =3.9.0
    - keras =2.12.0
    - tensorflow =2.12.1

test:
  commands:
    - interprete --help

build:
  noarch: python

about:
  home: https://github.com/genomenet/virusnet
  license: MIT
  license_file: LICENSE
  summary: A package for interpreting sequence regions of unkown origin.
  description: |
    Exporting the hidden states of various deepG models for further interpretation
