package:
  name: virusnet
  version: 0.0.4

source:
  path: ../virusnet/

requirements:
  host:
    - python =3.11.4
    - numpy >=1.17.0
    - r-base =4.3.1
    - r-devtools =2.4.5
    - r-optparse =1.7.3
    - r-remotes
    - r-zoo =1.8_12
    - h5py =3.9.0
    - keras =2.12.0
    - tensorflow =2.12.1

  run:
    - python =3.11.4
    - numpy >=1.17.0
    - r-base =4.3.1
    - r-devtools =2.4.5
    - r-optparse =1.7.3
    - r-remotes
    - r-zoo =1.8_12
    - h5py =3.9.0
    - keras =2.12.0
    - tensorflow =2.12.1

test:
  commands:
    - virusnet --help

build:
  noarch: python
  scripts:
      post-link: post-link.sh
about:
  home: https://github.com/genomenet/virusnet
  license: MIT
  license_file: LICENSE
  summary: A package for classifying virus using deep learning models.
  description: |
    VirusNet is a package that uses machine learning models to classify virus genus based on genomic sequences. 
    The model has been trained on high quality genomes from the International Committee on Taxonomy of Viruses (ICTV).
