name: Conda Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ['3.11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install Package
        shell: bash -l {0}
        run: |
          conda create --name test-env python=${{ matrix.python-version }}
          conda activate test-env
          conda install -c genomenet virusnet

      - name: Run Tests
        shell: bash -l {0}
        run: |
          chmod +x conda.recipe/run_test.sh
          conda.recipe/run_test.sh
