name: VirusNet Conda Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install Mamba
        shell: bash -l {0}
        run: |
          conda install mamba -c conda-forge

      - name: Install Package with Mamba
        shell: bash -l {0}
        run: |
          mamba create --name test-env python=${{ matrix.python-version }}
          conda activate test-env
          mamba install -c genomenet -c conda-forge virusnet

      - name: Check virusnet
        shell: bash -l {0}
        run: |
          virusnet -h

      - name: Run Tests
        shell: bash -l {0}
        run: |
          chmod +x virusnet/conda.recipe/run_test.sh
          virusnet/conda.recipe/run_test.sh
