name: Conda Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ['3.11']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Conda
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          conda create -n test-env python=${{ matrix.python-version }}
          conda activate test-env

      - name: Install Dependencies and Package
        run: |
          conda activate test-env
          conda install -c genomenet virusnet

      - name: Run Tests
        run: |
          conda activate test-env
          chmod +x conda.recipe/run_test.sh
          conda.recipe/run_test.sh
